# -*- coding: utf-8 -*-
"""Official WarmLink 3.0.4 resource catalog for PHNIX family 644.

App resource labels are evidence that the app knows a code, not proof that the
cloud accepts it, that it has a Modbus mapping, or that it may be written.
Keep this namespace separate from live-confirmed cloud and Modbus knowledge.
"""

from __future__ import annotations

WARMLINK_644_APP_SOURCE = "WarmLink 3.0.4 / Android param_644 resources"

WARMLINK_644_APP_PARAMETERS: dict[str, dict[str, object]] = {
    'A03': {"app_label": 'Shutdown Ambient Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A04': {"app_label": 'Antifreeze Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A05': {"app_label": 'Antifreeze Temp. Difference', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A06': {"app_label": 'Max. Exhaust Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A11': {"app_label": 'Enable Low Pressure Sensor', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A21': {"app_label": 'Ambient/Suction/Coil Sensor Type', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A22': {"app_label": 'Min. Antifreeze Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A23': {"app_label": 'Min. Outlet Water Temp. Protect', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A24': {"app_label": 'Excess Temp. Diff. Between Inlet and Outlet Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A25': {"app_label": 'Minimum Evaporation Temp. of Cooling', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A26': {"app_label": 'Refrigerant Type', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A27': {"app_label": 'Temp. Diff. of Limiting Frequency', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A28': {"app_label": 'Temp. Diff. Between Outlet and DHW Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A29': {"app_label": 'Enable High Pressure Sensor', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A30': {"app_label": 'Min. AT for Cooling', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A31': {"app_label": 'Electric Heater On AT', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A32': {"app_label": 'Electric Heater Delays Comp. On Time', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A33': {"app_label": 'Electric Heater Opening Temp. Diff', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A34': {"app_label": 'Crank Preheating Time', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A35': {"app_label": 'Electric Heater Off Temp. Diff', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A38': {"app_label": 'Low Pressure of Limiting Frequency', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A39': {"app_label": 'Max. Current Value', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'A40': {"app_label": 'Rated Water Flow', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'C01': {"app_label": 'Manual Comp. Frequency', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'C02': {"app_label": 'Min. Comp. Frequency', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'C03': {"app_label": 'Max. Comp. Frequency', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'C04': {"app_label": 'Model Selection', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'C05': {"app_label": 'Min. Comp. Frequency in Cooling at Low Ambient Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'C07': {"app_label": 'Resonance Point 1', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'C08': {"app_label": 'Resonance Point 2', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'C09': {"app_label": 'Resonance Point 3', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'C10': {"app_label": 'Min. Comp. Frequency in Heating at Low Ambient Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'C11': {"app_label": 'Max. Comp. Frequency in Cooling at High Ambient Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'C12': {"app_label": 'Max. Comp. Frequency in DHW mode.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D01': {"app_label": 'Ambient Temp. of Starting Defrosting', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D02': {"app_label": 'Heating Operation Time Before Defrosting', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D03': {"app_label": 'Interval Time Between Defrosting Cycles', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D04': {"app_label": 'Exhaust Temp. Correction for Defrosting Cycle', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D05_1': {"app_label": 'Defrosting Suction Pressure 1', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D05_2': {"app_label": 'Defrosting Suction Pressure 2', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D06': {"app_label": 'Defrosting Cycle Time Correction', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D07': {"app_label": 'Ambient Temp. of Start Sliding Defrosting', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D08': {"app_label": 'Suction Temp. of Start Sliding Defrosting', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D09': {"app_label": 'Ambient Temp. of Stop Sliding Defrosting', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D10': {"app_label": 'Suction Temp. of Stop Sliding Defrosting', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D11': {"app_label": 'Min. Inlet Water Temp. of Defrosting', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D12': {"app_label": 'Suction Pressure of Forced Defrosting', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D13': {"app_label": 'Heating Operation Time Before Forced Defrosting', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D14': {"app_label": 'Fan Motor Power Ratio to Extend Defrosting Cycle', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D15': {"app_label": 'Fan Motor Power Ratio to Enter Forced Defrosting', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D16': {"app_label": 'Max. Fan Motor Power to Enter Forced Defrosting', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D17': {"app_label": 'Coil Temp. of Exit Defrosting', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D18': {"app_label": 'Distributor Tube Temp. of Exit Defrosting', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D19': {"app_label": 'Max. Defrosting Time', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D20': {"app_label": 'Defrosting Frequency', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D21': {"app_label": 'Enable Electric Heater During Defrosting', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D22': {"app_label": 'Water Flow of Defrosting', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D23': {"app_label": 'Max. Defrosting Cycle by Fan Motor Power', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D24': {"app_label": 'Defrosting Heating Source in Heating / DHW Mode', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D25': {"app_label": 'Max. Water Temp. Decrease during Defrosting', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D26': {"app_label": 'Enable Defrosting Communication in Cascade', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'D30': {"app_label": 'Bottom Heater Delays Off Time after Defrost', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E01': {"app_label": 'EEV Adjust Mode', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E02': {"app_label": 'Target Superheat for Heating', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E03': {"app_label": 'EEV Initial Steps for Heating', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E03_1': {"app_label": 'EEV Initial Steps for Heating 1', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E03_2': {"app_label": 'EEV Initial Steps for Heating 2', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E03_3': {"app_label": 'EEV Initial Steps for Heating 3', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E03_4': {"app_label": 'EEV Initial Steps for Heating 4', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E03_5': {"app_label": 'EEV Initial Steps for Heating 5', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E07': {"app_label": 'EEV Min. Steps', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E07_1': {"app_label": 'EEV Min. Steps 1', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E07_2': {"app_label": 'EEV Min. Steps 2', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E07_3': {"app_label": 'EEV Min. Steps 3', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E07_4': {"app_label": 'EEV Min. Steps 4', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E07_5': {"app_label": 'EEV Min. Steps 5', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E08': {"app_label": 'EEV Initial Steps for Cooling', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E09': {"app_label": 'EVI EEV: Adjustment Mode', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E10': {"app_label": 'EVI EEV: Initial Steps', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E13': {"app_label": 'EVI EEV Target Superheat Degree', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E14': {"app_label": 'EVI EEV Min. Steps', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E17': {"app_label": 'Defrosting EEV Steps', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E18': {"app_label": 'Target Superheat for Cooling', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'E19': {"app_label": 'EEV Adjustment Range In Smart Mode', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'F01': {"app_label": 'Fan Motor Type', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'F02': {"app_label": 'Coil Temp. for Max. Fan Speed in Cooling', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'F03': {"app_label": 'Coil Temp. for Min. Fan Speed in Cooling', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'F05': {"app_label": 'Coil Temp. for Max. Fan Speed in Heating', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'F06': {"app_label": 'Coil Temp. for Min. Fan Speed in Heating', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'F10': {"app_label": 'Fan Quantity', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'F18': {"app_label": 'Min. Fan Speed in Cooling', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'F19': {"app_label": 'Min. Fan Speed in Heating', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'F22': {"app_label": 'Enable Manual-Control Fan Speed', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'F23': {"app_label": 'Rated DC Fan Motor Speed', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'F25': {"app_label": 'Max. Fan Speed in Cooling', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'F26': {"app_label": 'Max. Fan Speed in Heating', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'F27': {"app_label": 'Fan Motor Power Curve', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'F28': {"app_label": 'CT to Reduce Two Fans to One in Cooling', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'F29': {"app_label": 'CT to Stop Single Fan in Cooling', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'G01': {"app_label": 'Disinfection Water Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'G02': {"app_label": 'Time Duration of Disinfection', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'G03': {"app_label": 'Disinfection Starting Time', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'G04': {"app_label": 'Interval Period of Disinfection', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'G05': {"app_label": 'Enable Disinfection', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H01': {"app_label": 'Enable Power-off Memory', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H05': {"app_label": 'Enable Cooling Function', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H07': {"app_label": 'Display Control/Remote Control', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H10': {"app_label": 'Unit Address', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H18': {"app_label": 'Electric Heater Stage', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H20': {"app_label": '3-Way Valve Polarity', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H21': {"app_label": 'Temperature Unit', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H22': {"app_label": 'Enable Silent Mode', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H25': {"app_label": 'Temp. Control Selection', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H27': {"app_label": 'Enable EVI', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H28': {"app_label": 'Heating/Cooling and Hot Water Function Enabled', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H29': {"app_label": 'Operation Code', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H30': {"app_label": 'Indoor Unit Type', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H31': {"app_label": 'Circulation Pump Type', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H32': {"app_label": 'Force Switch Mode Time', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H33': {"app_label": 'Fan Motor Driver and Comp. Driver Integrated', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H36': {"app_label": 'Enable Positive Weather Compensation', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H37': {"app_label": 'DHW Temp. Sourcing', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H40': {"app_label": 'External Pump Selection', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H42': {"app_label": 'AT for Bottom Plate Heater Turned On', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'H43': {"app_label": 'Normal/Eco', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'O01': {"app_label": 'Compressor', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'O03': {"app_label": 'Fan Motor:High Speed', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'O04': {"app_label": 'Fan Motor:Low Speed', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'O05': {"app_label": 'Main Circulation Pump', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'O06': {"app_label": 'DHW Pump', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'O07': {"app_label": '4-Way Valve', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'O08': {"app_label": 'Electric Heater Stage 1', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'O09': {"app_label": 'Electric Heater Stage 2', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'O10': {"app_label": 'Hot Water 3-Way Valve', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'O11': {"app_label": 'Alarm', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'O12': {"app_label": 'Crankcase Heater', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'O13': {"app_label": 'Bottom Plate Heater', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'O15': {"app_label": 'EEV Steps', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'O17': {"app_label": 'EEV(EVI) Steps', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'O21': {"app_label": 'Air-Conditioning Pump', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'O22': {"app_label": 'Electric Heating of Waterway(Hydraulic Module)', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'O23': {"app_label": 'Electric Heating of Water Tank(Hydraulic Module)', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'P01': {"app_label": 'Main Circulation Pump Operation Mode', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'P02': {"app_label": 'Interval Time', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'P03': {"app_label": 'Operation Duration Time', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'P05': {"app_label": 'DHW Pump Operation Mode', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'P06': {"app_label": 'Main Circulation Pump Manual Control', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'P08': {"app_label": 'Main Circulation Pump Rated Power', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'P09': {"app_label": 'Circulation Pump Protection Period', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'P10': {"app_label": 'Speed of Circulation Pump', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'P11': {"app_label": 'Target Temp. Diff. for Pump Speed Control', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'P12': {"app_label": 'Pump Speed Adjust Range for Each Period', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'P13': {"app_label": 'Refill Valve Start Cycle (for IDU)', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'P14': {"app_label": 'Refill Valve Working Duration (for IDU)', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'P15': {"app_label": 'Target Water Pressure (for IDU)', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'P16': {"app_label": 'Stop Refilling Pressure Diff. (for IDU)', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R01': {"app_label": 'DHW Target Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R02': {"app_label": 'Heating Target Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R03': {"app_label": 'Cooling Target Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R04': {"app_label": 'Temp. Diff. for Power-on in Heating', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R05': {"app_label": 'Temp. Diff. for Standby in Heating', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R06': {"app_label": 'Temp. Diff. for Power-on in Cooling', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R07': {"app_label": 'Temp. Diff. for Standby in Cooling', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R08': {"app_label": 'Min. Cooling Target Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R09': {"app_label": 'Max. Cooling Target Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R10': {"app_label": 'Min. Heating Target Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R11': {"app_label": 'Max. Heating Target Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R15': {"app_label": 'Temp. Diff. of Exiting Overhigh Outlet Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R16': {"app_label": 'Temp. Diff. for Power-on in DHW', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R17': {"app_label": 'Temp. Diff. for Standby in DHW', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R29': {"app_label": 'Low AT for Water Temp. Limit On', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R30': {"app_label": 'Low AT for Water Temp. Limit Off', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R31': {"app_label": 'Max. Limit Outlet Water Temp. at Low AT', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R32': {"app_label": 'High AT for Water Temp. Limit On', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R33': {"app_label": 'High AT for Water Temp. Limit Off', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R34': {"app_label": 'Max. Limit Outlet Water Temp. at High AT', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R35': {"app_label": 'Location of Electric Heater', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R36': {"app_label": 'Min. DHW Target Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R37': {"app_label": 'Max. DHW Target Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R39': {"app_label": 'AT for Auto-Start Heating Mode', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R42': {"app_label": 'Max. Outlet Water Temp. in Heating', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R43': {"app_label": 'Max. Limit Target Water Temp. at Low AT in Heating', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R44': {"app_label": 'Max. Limit Target Water Temp. at High AT in Heating', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R45': {"app_label": 'AT to Start Electric Heater Without Delay', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R46': {"app_label": 'Temp. Diff. between Max. DHW Target Temp. & Max. Outlet Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R60': {"app_label": 'AT to Start Frequency Limit in Cooling', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R61': {"app_label": 'AT to Stop Frequency Limit in Cooling', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R62': {"app_label": 'Max. Heat Pump Outlet Water Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R70': {"app_label": 'Target Room Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R71': {"app_label": 'Room Temp. Diff. for Power-on in Heating', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R72': {"app_label": 'Room Temp. Diff. for Standby in Heating', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R73': {"app_label": 'Room Temp. Diff. for Power-on in Cooling', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'R74': {"app_label": 'Room Temp. Diff. for Standby in Cooling', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'S01': {"app_label": 'High Pressure', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'S02': {"app_label": 'Low Pressure', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'S03': {"app_label": 'Flow Switch', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'S04': {"app_label": 'Electric Heater Overload', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'S05': {"app_label": 'Remote Switch', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'S06': {"app_label": 'Air Conditioning Mode Switch', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'S07': {"app_label": 'Hot Water Switch', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'S10': {"app_label": 'Air Conditioning Switch', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T01': {"app_label": 'Inlet Water Temp', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T02': {"app_label": 'Outlet Water Temp', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T03': {"app_label": 'Coil Temp', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T04': {"app_label": 'Ambient Temp', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T05': {"app_label": 'Suction Temp', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T06': {"app_label": 'Antifreeze Temp1', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T07': {"app_label": 'Buffer Tank Temp', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T08': {"app_label": 'DHW Temp', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T09': {"app_label": 'Room Temp', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T10': {"app_label": 'Inlet Temp(EVI)', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T11': {"app_label": 'Outlet Temp(EVI)', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T12': {"app_label": 'Exhaust Temp', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T15': {"app_label": 'Pressure', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T27': {"app_label": 'Speed of Fan Motor1', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T28': {"app_label": 'Speed of Fan Motor2', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T29': {"app_label": 'Target Speed of Fan Motor', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T30': {"app_label": 'Compressor Frequency', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T31': {"app_label": 'Operation Frequency of Compressor', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T32': {"app_label": 'Max Frequency Allowed for Driver', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T33': {"app_label": 'IPM Shutdown Protection Temp. Due to Overheat', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T34': {"app_label": 'AC Input Voltage', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T35': {"app_label": 'AC Input Current', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T36': {"app_label": 'Phase Current of Compressor', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T37': {"app_label": 'DC Bus Voltage', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T38': {"app_label": 'IPM Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T39': {"app_label": 'Water Flow', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T40': {"app_label": 'Inlet Water Temp of Air-Conditioning', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T41': {"app_label": 'Outlet Water Temp of Air-Conditioning', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T42': {"app_label": 'Outlet Water Temp of Water Mixer', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T43': {"app_label": 'Inlet Water Temp of Hot Water', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T44': {"app_label": 'Outlet Water Temp of Hot Water', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T46': {"app_label": 'Fan Motor Module IPM Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T47': {"app_label": 'Fan Motor Module Power', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'T48': {"app_label": 'Fan Motor Module Current', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z01': {"app_label": 'Enable Multi-Zone Control', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z02': {"app_label": 'Zone 1 Target RT', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z03': {"app_label": 'Zone 1 RT Diff. to Start', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z04': {"app_label": 'Zone 2 Target RT', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z05': {"app_label": 'Zone 2 RT Diff. to Start', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z06': {"app_label": 'Zone 1 Heating Target Outlet WT', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z07': {"app_label": 'Zone 2 Mixing Target Outlet WT', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z08': {"app_label": 'Mixing Valve Manual Adjustment Ratio (0% for Auto Control)', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z09': {"app_label": 'Mixing Valve Opening Time', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z10': {"app_label": 'Mixing Valve Closing Time', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z11': {"app_label": 'Mixing Valve Adjustment P(PID)', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z12': {"app_label": 'Mixing Valve Adjustment I(PID)', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z13': {"app_label": 'Mixing Valve PID Period', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z14': {"app_label": 'Steps of Mixing Valve in Cooling', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z15': {"app_label": 'Zone 2 Max. Water Target Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z16': {"app_label": 'Enable AT Compensation Curve Zone 1', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z17': {"app_label": 'Enable AT Compensation Curve Zone 2', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z19': {"app_label": 'Diff. of No Pump On at Low Water Temp.', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
    'Z20': {"app_label": 'Enable Zone 1 Water Pump in Cooling', "app_family": "644", "source": WARMLINK_644_APP_SOURCE, "app_known": True, "query_candidate": True, "write_allowed": False},
}

# Fault resources have an independent namespace: e.g. fault F01 is not parameter F01.
WARMLINK_644_APP_FAULTS: dict[str, dict[str, str]] = {
    'E003': {"app_label": 'Driver Board Self Test', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E032': {"app_label": 'Flow Switch Protection', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E032_3': {"app_label": 'Flow Switch Protection 3+', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E04': {"app_label": 'Aux Superheat Protection', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E04_3': {"app_label": 'Aux Superheat Protection 3+', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E051': {"app_label": 'Compressor Overcurrent Shutdown Fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E06': {"app_label": 'Inlet and outlet temperature too big', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E065': {"app_label": 'Outlet Water Over temperature protection', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E065_3': {"app_label": 'Outlet Water Over temperature protection 3+', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E06_3': {"app_label": 'Excess Water Temperature Diffience Protion', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E071': {"app_label": 'Outlet Water Low temperature protection', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E071_3': {"app_label": 'Outlet Water Low temperature protection 3+', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E08': {"app_label": 'Communication Fault between the mainboard and display', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E081': {"app_label": 'Communication Fault(between speed control module1 and mainboard)', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E082': {"app_label": 'Communication Fault(between speed control module2 and mainboard)', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E084': {"app_label": 'The Wire Controller Does Not Match The Mainboard', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E08C': {"app_label": 'Communication Fault between the mainboard and Hydraulic Module', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E101': {"app_label": 'System1:Compressor Overcurrent protection', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E101_3': {"app_label": 'System1:Compressor Overcurrent protection 3+', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E103': {"app_label": 'Fan Motor1 Overload Protion', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E11': {"app_label": 'System1: High Pressure Protection', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E11_3': {"app_label": 'System1: High Pressure Protection 3+', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E12': {"app_label": 'System1: Low Pressure Protection', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E12_3': {"app_label": 'System1: Low Pressure Protection 3+', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E171': {"app_label": 'System1:Antifreeze protection', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E171_3': {"app_label": 'System1:Antifreeze protection 3+', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E19': {"app_label": 'Prim Anti-freezing Protion', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E201': {"app_label": 'System2:Compressor Overcurrent protection', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E201_3': {"app_label": 'System2:Compressor Overcurrent protection 3+', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E203': {"app_label": 'Fan Motor2 Overload Protion', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E21': {"app_label": 'System2: High Pressure Protection', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E21_3': {"app_label": 'System2: High Pressure Protection 3+', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E22': {"app_label": 'System2: Low Pressure Protection', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E22_3': {"app_label": 'System2: Low Pressure Protection 3+', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E271': {"app_label": 'System2:Antifreeze', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E271_3': {"app_label": 'System2:Antifreeze protection 3+', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'E29': {"app_label": 'Secondary Anti-freezing Protion', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F00': {"app_label": 'IPM Overcurrent Shutdown Fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F01': {"app_label": 'Compressor Activation Failure', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F03': {"app_label": 'PFC fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F031': {"app_label": 'Fan Motor1 Fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F032': {"app_label": 'Fan Motor2 Fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F05': {"app_label": 'DC Bus Overload', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F051': {"app_label": 'Communication Fault (Inverter Board)', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F06': {"app_label": 'DC Bus Underload', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F07': {"app_label": 'AC Input Underload', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F08': {"app_label": 'AC Input Overload', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F081': {"app_label": 'Communication Fault（Drive Board）', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F09': {"app_label": 'Input Voltage Sample Fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F10': {"app_label": 'Comm. Err DSP-PFC', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F11': {"app_label": 'Communication Fault (DSP)', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F12': {"app_label": 'Communication Fault (Inverter Board)', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F13': {"app_label": 'IPM Overheat Stop', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F15': {"app_label": 'Input Voltage Lacking Phase', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F151': {"app_label": 'Communication Fault DSP-MainBoard', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F16': {"app_label": 'Weak Magnetic Warn', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F17': {"app_label": 'Sensor Fault of Module/Radiator', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F18': {"app_label": 'IPM Current Sample Fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F20': {"app_label": 'IGBT Power Device Overhear Alarm', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F21': {"app_label": 'Overload Alarm', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F22': {"app_label": 'AC Input OverCurrent Alarm', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F23': {"app_label": 'EEPROM Error Warn', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F24': {"app_label": 'Destroyed EEPROM Activation Ban Alarm', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F25': {"app_label": 'V15V Over/Undervoltage Fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F26': {"app_label": 'IGBT Power Device Overheat Fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'F33': {"app_label": 'Compressor Current Frequency Reduction Alarm', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P01': {"app_label": 'Inlet Temperature Sensor Fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P013': {"app_label": 'Inlet Water Temperature Sensor Fault of Air-Conditioning', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P018': {"app_label": 'Inlet Water Temperature Sensor Fault of Hot Water', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P02': {"app_label": 'Outlet Temp Sensor Fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P023': {"app_label": 'Outlet Water Temperature Sensor Fault of Air-Conditioning', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P028': {"app_label": 'Outlet Water Temperature Sensor Fault of Hot Water', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P02A': {"app_label": 'Outlet Water Temperature Sensor Fault of Water Mixer', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P03': {"app_label": 'DHW Water Tank Temp Sensor fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P03A': {"app_label": 'Heating expansion tank temperature sensor failure', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P04': {"app_label": 'Ambient Temperature Sensor Fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P101': {"app_label": 'System1:Inlet Sensor(EVI) fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P102': {"app_label": 'System2:Inlet Sensor(EVI) fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P153': {"app_label": 'Syst1:Coil temperature Sensor1', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P17': {"app_label": 'System1:Suction temp Sensor', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P181': {"app_label": 'System1:Exhaust temperature Sensor fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P182': {"app_label": 'System1:Exhaust Over temperature protection', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P182_3': {"app_label": 'System1:Exhaust Over temperature protection 3+', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P191': {"app_label": 'System1:Antifreeze Sensor1 fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P193': {"app_label": 'System1:Antifreeze Sensor2 fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P281': {"app_label": 'System2:Exhaust Temperature Sensor fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P282': {"app_label": 'System2:Exhaust Over temperature protection', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P282_3': {"app_label": 'System2:Exhaust Over temperature protection 3+', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P291': {"app_label": 'System2:Antifreeze Sensor1 fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P293': {"app_label": 'System2:Antifreeze Sensor2 fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'P42': {"app_label": 'Room Temperature Sensor Fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'PP11': {"app_label": 'Syst1:Pressure Sensor fault', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
    'TP': {"app_label": 'Low AT Protection', "app_family": "644", "source": "WarmLink 3.0.4 fault resources"},
}

_RESOURCE_TO_CLOUD = {
    **{f"D05_{i}": f"D05-{i}" for i in range(1, 3)},
    **{f"E03_{i}": f"E03-{i}" for i in range(1, 6)},
    **{f"E07_{i}": f"E07-{i}" for i in range(1, 6)},
}

def app_644_parameter(code: str) -> dict[str, object] | None:
    value = WARMLINK_644_APP_PARAMETERS.get(str(code))
    return dict(value) if value is not None else None

def app_644_label(code: str) -> str:
    value = WARMLINK_644_APP_PARAMETERS.get(str(code), {})
    return str(value.get("app_label") or "")

def app_644_cloud_code(resource_code: str) -> str:
    """Use observed dash spelling for resource suffixes; never query both forms."""
    code = str(resource_code)
    return _RESOURCE_TO_CLOUD.get(code, code)

def known_644_codes(*, cloud_spelling: bool = False) -> tuple[str, ...]:
    codes = WARMLINK_644_APP_PARAMETERS
    if not cloud_spelling:
        return tuple(codes)
    return tuple(dict.fromkeys(app_644_cloud_code(code) for code in codes))
