# -*- coding: utf-8 -*-
"""WarmLink/Linked-Go Cloud Codes und Mapping fuer FoxAir / Phnix Control.

WarmLink/Linked-Go API mapping inspired by srbjessen/ha-warmlink, licensed
under MIT. Original reverse engineering credited there to zyznos321/warmlink.

V0.2.44: Die Code-Liste wurde aus einem erfolgreichen dump_all-Lauf erweitert
(391 Rueckgabezeilen). Feste Modbus-Zuordnungen sind als Mapping mit
confidence=confirmed/candidate/unknown markiert, damit falsche Zuordnungen nicht
still als Wahrheit behandelt werden.
"""

from __future__ import annotations

WARMLINK_CLOUD_CREDIT = (
    "WarmLink/Linked-Go API mapping inspired by srbjessen/ha-warmlink, "
    "licensed under MIT. Original reverse engineering credited there to "
    "zyznos321/warmlink."
)

# Aus warmlink_all_flat.csv / dump_all-Lauf, Reihenfolge beibehalten.
ALL_WARMLINK_CLOUD_CODES: list[str] = ['A03',
 'A04',
 'A05',
 'A06',
 'A11',
 'A21',
 'A22',
 'A23',
 'A24',
 'A25',
 'A26',
 'A27',
 'A28',
 'A29',
 'A30',
 'A31',
 'A32',
 'A33',
 'A34',
 'A35',
 'A38',
 'A39',
 'A40',
 'C01',
 'C02',
 'C03',
 'C04',
 'C05',
 'C07',
 'C08',
 'C09',
 'C10',
 'C11',
 'C12',
 'D01',
 'D02',
 'D03',
 'D04',
 'D05-1',
 'D05-2',
 'D06',
 'D07',
 'D08',
 'D09',
 'D10',
 'D11',
 'D12',
 'D13',
 'D14',
 'D15',
 'D16',
 'D17',
 'D18',
 'D19',
 'D20',
 'D21',
 'D22',
 'D23',
 'D24',
 'D25',
 'D26',
 'D30',
 'E01',
 'E02',
 'E03',
 'E03-1',
 'E03-2',
 'E03-3',
 'E03-4',
 'E03-5',
 'E07',
 'E07-1',
 'E07-2',
 'E07-3',
 'E07-4',
 'E07-5',
 'E08',
 'E09',
 'E10',
 'E13',
 'E14',
 'E17',
 'E18',
 'E19',
 'F01',
 'F02',
 'F03',
 'F05',
 'F06',
 'F10',
 'F14',
 'F15',
 'F17',
 'F18',
 'F19',
 'F22',
 'F23',
 'F25',
 'F26',
 'F27',
 'F28',
 'F29',
 'G01',
 'G02',
 'G03',
 'G04',
 'G05',
 'H01',
 'H05',
 'H07',
 'H10',
 'H18',
 'H20',
 'H21',
 'H22',
 'H25',
 'H27',
 'H28',
 'H29',
 'H30',
 'H31',
 'H32',
 'H33',
 'H36',
 'H37',
 'H40',
 'H42',
 'H43',
 'H45',
 'O01~014',
 'O01~023',
 'O15',
 'O17',
 'P01',
 'P02',
 'P03',
 'P05',
 'P06',
 'P08',
 'P09',
 'P10',
 'P11',
 'P12',
 'P13',
 'P14',
 'P15',
 'P16',
 'R01',
 'R02',
 'R03',
 'R04',
 'R05',
 'R06',
 'R07',
 'R08',
 'R09',
 'R10',
 'R11',
 'R15',
 'R16',
 'R17',
 'R29',
 'R30',
 'R31',
 'R32',
 'R33',
 'R34',
 'R35',
 'R36',
 'R37',
 'R39',
 'R42',
 'R43',
 'R44',
 'R45',
 'R46',
 'R60',
 'R61',
 'R62',
 'R70',
 'R71',
 'R72',
 'R73',
 'R74',
 'S01~S10',
 'T01',
 'T02',
 'T03',
 'T04',
 'T05',
 'T06',
 'T07',
 'T08',
 'T09',
 'T10',
 'T11',
 'T12',
 'T15',
 'T27',
 'T28',
 'T29',
 'T30',
 'T31',
 'T32',
 'T33',
 'T34',
 'T35',
 'T36',
 'T37',
 'T38',
 'T39',
 'T40',
 'T41',
 'T42',
 'T43',
 'T44',
 'T46',
 'T47',
 'T48',
 'Z01',
 'Z02',
 'Z03',
 'Z04',
 'Z05',
 'Z06',
 'Z07',
 'Z08',
 'Z09',
 'Z10',
 'Z11',
 'Z12',
 'Z13',
 'Z14',
 'Z15',
 'Z16',
 'Z17',
 'Z19',
 'Z20',
 'Z21',
 'KG1',
 'KG2',
 'KG3',
 'KG4',
 'KG5',
 'KG6',
 'KG7',
 'KG8',
 'KG9',
 'KG10',
 'KG11',
 'KG12',
 'KG13~KG28',
 'KG29~KG44',
 'KG45~KG60',
 'DP1',
 'DP2',
 'DP3',
 'DP4',
 'DP5',
 'DP6',
 'M1 Mode',
 'M1 Start',
 'M1 End',
 'M1 Heating Target',
 'M1 Cooling Target',
 'M1 Hot Water Target',
 'M1 Max. Power',
 'M2 Mode',
 'M2 Start',
 'M2 End',
 'M2 Heating Target',
 'M2 Cooling Target',
 'M2 Hot Water Target',
 'M2 Max. Power',
 'M3 Mode',
 'M3 Start',
 'M3 End',
 'M3 Heating Target',
 'M3 Cooling Target',
 'M3 Hot Water Target',
 'M3 Max. Power',
 'M4 Mode',
 'M4 Start',
 'M4 End',
 'M4 Heating Target',
 'M4 Cooling Target',
 'M4 Hot Water Target',
 'M4 Max. Power',
 'M5 Mode',
 'M5 Start',
 'M5 End',
 'M5 Heating Target',
 'M5 Cooling Target',
 'M5 Hot Water Target',
 'M5 Max. Power',
 'M6 Mode',
 'M6 Start',
 'M6 End',
 'M6 Heating Target',
 'M6 Cooling Target',
 'M6 Hot Water Target',
 'M6 Max. Power',
 'M1_2 Enalbe',
 'M3_4 Enalbe',
 'M5_6 Enalbe',
 'W1 Start',
 'W1 End',
 'W1_2 Enalbe',
 'W2 Start',
 'W2 End',
 'W3 Start',
 'W3 End',
 'W3 Enalbe',
 'SG01',
 'SG02',
 'SG03',
 'SG04',
 'SG05',
 'SG06',
 'SG07',
 'SG08',
 'SG Status',
 'Timer_Mute_On_En',
 'Timer_Mute_Off_En',
 'TimerMuteOnHour',
 'TimerMuteOnMinute',
 'TimerMuteOffHour',
 'TimerMuteOffMinute',
 'Fault1',
 'Fault5',
 'Fault6',
 'Zone 1 Room Temp',
 'Zone 2 Room Temp',
 'Zone 2 Mixing Temp',
 'Zone 2 Water Target',
 'Zone 2 Cure Slope',
 'Zone 2 Curve Offset',
 'Power',
 'Mode',
 'ModeState',
 'hanControl',
 'app_heartbeat',
 'compensate_slope',
 'compensate_offset',
 'code_version',
 'MainBoard Version',
 '1206',
 '1208',
 '2014',
 '2146',
 'E035',
 'E001',
 'E002',
 'E003',
 'E004',
 'E005',
 'E006',
 'E011',
 'E012',
 'E015',
 'E016',
 'E020',
 'E021',
 'E022',
 'E023',
 'E024',
 'E025',
 'E026',
 'E027',
 'E028',
 'E029',
 'E030',
 'E031',
 'E032',
 'E033',
 'E034',
 'E036',
 'E037',
 'E038',
 'E039',
 'E040',
 'E041',
 'E042',
 'E043',
 'E044',
 'E045',
 'Fault2',
 'Fault3',
 'Fault4',
 'Fault7',
 'Fault8']

# Default = alles, was der dump_all-Lauf sinnvoll abgefragt hat.
DEFAULT_WARMLINK_CLOUD_CODES: list[str] = list(ALL_WARMLINK_CLOUD_CODES)

WARMLINK_PRODUCT_IDS: list[str] = [
    "1194901186696777728", "1239430558124097536", "1255021944487620608",
    "1280068488723034112", "1339750000640499712", "1605555198352117760",
    "1531069503612518401", "1334333994707222528", "1314389730321776640",
    "1534426457089150976", "1430840899188973568", "1151012720393330688",
    "1390463737449857024", "1442056800068329472", "1787637595964661762",
    "1904737978748719105", "1659079112307445760", "1898923361595772930",
    "1631478423544852480", "1802975574960046081", "1501438265440362496",
    "1713838037212577792", "1899374754815238145", "1544970221549498368",
    "1559733647991496705", "1506552523736190976", "1473911871244337152",
    "1552190345066967040", "1534450342119510016", "1480699335514533888",
]

WARMLINK_CLOUD_CODE_HINTS: dict[str, dict[str, object]] = {'1206': {'cloud_dataType': 'DIGI1', 'rangeEnd': '500', 'rangeStart': '0'},
 '1208': {'cloud_dataType': 'DIGI1', 'rangeEnd': '500', 'rangeStart': '0'},
 '2014': {'cloud_dataType': 'TEMP', 'confidence': 'candidate', 'modbus_register': 2014, 'name': 'Cloud-Code 2014', 'unit': '°C'},
 '2146': {'cloud_dataType': 'BINARY',
          'confidence': 'candidate',
          'dataType': 'bitword16',
          'modbus_register': 2146,
          'name': 'Cloud-Code 2146'},
 'A03': {'cloud_dataType': 'TEMP', 'rangeEnd': '10', 'rangeStart': '-40'},
 'A04': {'cloud_dataType': 'TEMP', 'rangeEnd': '10', 'rangeStart': '3.00'},
 'A05': {'cloud_dataType': 'TEMP', 'rangeEnd': '50', 'rangeStart': '1'},
 'A06': {'cloud_dataType': 'TEMP', 'rangeEnd': '130', 'rangeStart': '60'},
 'A11': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'A21': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'A22': {'cloud_dataType': 'TEMP', 'rangeEnd': '10', 'rangeStart': '-20'},
 'A23': {'cloud_dataType': 'TEMP', 'rangeEnd': '20', 'rangeStart': '-30'},
 'A24': {'cloud_dataType': 'TEMP', 'rangeEnd': '30', 'rangeStart': '0'},
 'A25': {'cloud_dataType': 'TEMP', 'rangeEnd': '30', 'rangeStart': '-50'},
 'A26': {'cloud_dataType': 'DIGI1', 'rangeEnd': '99', 'rangeStart': '0'},
 'A27': {'cloud_dataType': 'TEMP', 'rangeEnd': '95', 'rangeStart': '-20'},
 'A28': {'cloud_dataType': 'TEMP', 'rangeEnd': '95', 'rangeStart': '-20'},
 'A29': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'A30': {'cloud_dataType': 'TEMP', 'rangeEnd': '60', 'rangeStart': '-30'},
 'A31': {'cloud_dataType': 'TEMP', 'rangeEnd': '60', 'rangeStart': '-30'},
 'A32': {'cloud_dataType': 'DIGI1', 'rangeEnd': '999', 'rangeStart': '10'},
 'A33': {'cloud_dataType': 'TEMP', 'rangeEnd': '20', 'rangeStart': '0'},
 'A34': {'cloud_dataType': 'DIGI1', 'rangeEnd': '360', 'rangeStart': '0'},
 'A35': {'cloud_dataType': 'TEMP',
         'confidence': 'confirmed',
         'local_code': 'A35',
         'modbus_register': 1031,
         'name': 'Electric Heater Off Temp Diff / E-Heizer Ausschalt-Temperaturdifferenz',
         'rangeEnd': '30',
         'rangeStart': '0',
         'unit': '°C'},
 'A38': {'cloud_dataType': 'DIGI5', 'rangeEnd': '20.0', 'rangeStart': '0.0'},
 'A39': {'cloud_dataType': 'DIGI5', 'rangeEnd': '50.0', 'rangeStart': '0.0'},
 'A40': {'cloud_dataType': 'DIGI9',
         'confidence': 'confirmed',
         'local_code': 'A40',
         'modbus_register': 1344,
         'name': 'Rated Water Flow / Nenn-Durchfluss',
         'note': 'Flow/Durchfluss, z.B. 0.5 m³/h',
         'rangeEnd': '9.99',
         'rangeStart': '0.00',
         'unit': 'm³/h'},
 'C01': {'cloud_dataType': 'DIGI1', 'rangeEnd': '120', 'rangeStart': '0'},
 'C02': {'cloud_dataType': 'DIGI1', 'rangeEnd': '60', 'rangeStart': '20'},
 'C03': {'cloud_dataType': 'DIGI1', 'rangeEnd': '120', 'rangeStart': '30'},
 'C04': {'cloud_dataType': 'DIGI1', 'rangeEnd': '100', 'rangeStart': '0'},
 'C05': {'cloud_dataType': 'DIGI1', 'rangeEnd': '60', 'rangeStart': '0'},
 'C07': {'cloud_dataType': 'DIGI1', 'rangeEnd': '120', 'rangeStart': '0'},
 'C08': {'cloud_dataType': 'DIGI1', 'rangeEnd': '120', 'rangeStart': '0'},
 'C09': {'cloud_dataType': 'DIGI1', 'rangeEnd': '120', 'rangeStart': '0'},
 'C10': {'cloud_dataType': 'DIGI1', 'rangeEnd': '120', 'rangeStart': '0'},
 'C11': {'cloud_dataType': 'DIGI1', 'rangeEnd': '120', 'rangeStart': '0'},
 'C12': {'cloud_dataType': 'DIGI1', 'rangeEnd': '90', 'rangeStart': '30'},
 'D01': {'cloud_dataType': 'TEMP', 'rangeEnd': '45', 'rangeStart': '-37'},
 'D02': {'cloud_dataType': 'DIGI1', 'rangeEnd': '120', 'rangeStart': '0'},
 'D03': {'cloud_dataType': 'DIGI1', 'rangeEnd': '90', 'rangeStart': '10'},
 'D04': {'cloud_dataType': 'TEMP', 'rangeEnd': '150', 'rangeStart': '0'},
 'D05-1': {'cloud_dataType': 'DIGI5', 'rangeEnd': '45', 'rangeStart': '0'},
 'D05-2': {'cloud_dataType': 'DIGI5', 'rangeEnd': '45', 'rangeStart': '0'},
 'D06': {'cloud_dataType': 'DIGI1', 'rangeEnd': '120', 'rangeStart': '0'},
 'D07': {'cloud_dataType': 'TEMP', 'rangeEnd': '45', 'rangeStart': '-37'},
 'D08': {'cloud_dataType': 'TEMP', 'rangeEnd': '45', 'rangeStart': '-37'},
 'D09': {'cloud_dataType': 'TEMP', 'rangeEnd': '45', 'rangeStart': '-37'},
 'D10': {'cloud_dataType': 'TEMP', 'rangeEnd': '45', 'rangeStart': '-37'},
 'D11': {'cloud_dataType': 'TEMP', 'rangeEnd': '65', 'rangeStart': '4'},
 'D12': {'cloud_dataType': 'DIGI5', 'rangeEnd': '45', 'rangeStart': '0'},
 'D13': {'cloud_dataType': 'DIGI1', 'rangeEnd': '360', 'rangeStart': '0'},
 'D14': {'cloud_dataType': 'DIGI9', 'rangeEnd': '5', 'rangeStart': '0'},
 'D15': {'cloud_dataType': 'DIGI9', 'rangeEnd': '5', 'rangeStart': '0'},
 'D16': {'cloud_dataType': 'DIGI1', 'rangeEnd': '1000', 'rangeStart': '50'},
 'D17': {'cloud_dataType': 'TEMP', 'rangeEnd': '80', 'rangeStart': '-37'},
 'D18': {'cloud_dataType': 'TEMP', 'rangeEnd': '80', 'rangeStart': '-37'},
 'D19': {'cloud_dataType': 'DIGI1', 'rangeEnd': '20', 'rangeStart': '0'},
 'D20': {'cloud_dataType': 'DIGI1', 'rangeEnd': '90', 'rangeStart': '30'},
 'D21': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'D22': {'cloud_dataType': 'DIGI9', 'rangeEnd': '50', 'rangeStart': '0'},
 'D23': {'cloud_dataType': 'DIGI1', 'rangeEnd': '240', 'rangeStart': '0'},
 'D24': {'cloud_dataType': 'ENUM', 'rangeEnd': '2', 'rangeStart': '0'},
 'D25': {'cloud_dataType': 'TEMP', 'rangeEnd': '65', 'rangeStart': '2'},
 'D26': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'D30': {'cloud_dataType': 'DIGI1', 'rangeEnd': '60', 'rangeStart': '0'},
 'DP1': {'cloud_dataType': 'ENUM', 'rangeEnd': '2', 'rangeStart': '0'},
 'DP2': {'cloud_dataType': 'TEMP', 'rangeEnd': '10', 'rangeStart': '-10'},
 'DP3': {'cloud_dataType': 'TEMP', 'rangeEnd': '25', 'rangeStart': '4'},
 'DP4': {'cloud_dataType': 'TEMP'},
 'DP5': {'cloud_dataType': 'TEMP'},
 'DP6': {'cloud_dataType': 'TEMP'},
 'E001': {},
 'E002': {},
 'E003': {},
 'E004': {},
 'E005': {},
 'E006': {},
 'E01': {'cloud_dataType': 'ENUM',
         'confidence': 'confirmed',
         'local_code': 'E01',
         'modbus_register': 1131,
         'name': 'E01',
         'rangeEnd': '2',
         'rangeStart': '0'},
 'E011': {},
 'E012': {},
 'E015': {},
 'E016': {},
 'E02': {'cloud_dataType': 'TEMP', 'rangeEnd': '20', 'rangeStart': '-20'},
 'E020': {},
 'E021': {},
 'E022': {},
 'E023': {},
 'E024': {},
 'E025': {},
 'E026': {},
 'E027': {},
 'E028': {},
 'E029': {},
 'E03': {'cloud_dataType': 'DIGI1', 'rangeEnd': '500', 'rangeStart': '0'},
 'E03-1': {'cloud_dataType': 'DIGI1', 'rangeEnd': '500', 'rangeStart': '0'},
 'E03-2': {'cloud_dataType': 'DIGI1', 'rangeEnd': '500', 'rangeStart': '0'},
 'E03-3': {'cloud_dataType': 'DIGI1', 'rangeEnd': '500', 'rangeStart': '0'},
 'E03-4': {'cloud_dataType': 'DIGI1', 'rangeEnd': '500', 'rangeStart': '0'},
 'E03-5': {'cloud_dataType': 'DIGI1', 'rangeEnd': '500', 'rangeStart': '0'},
 'E030': {},
 'E031': {},
 'E032': {},
 'E033': {},
 'E034': {},
 'E035': {},
 'E036': {},
 'E037': {},
 'E038': {},
 'E039': {},
 'E040': {},
 'E041': {},
 'E042': {},
 'E043': {},
 'E044': {},
 'E045': {},
 'E07': {'cloud_dataType': 'DIGI1', 'rangeEnd': '500', 'rangeStart': '0'},
 'E07-1': {'cloud_dataType': 'DIGI1', 'rangeEnd': '500', 'rangeStart': '0'},
 'E07-2': {'cloud_dataType': 'DIGI1', 'rangeEnd': '500', 'rangeStart': '0'},
 'E07-3': {'cloud_dataType': 'DIGI1', 'rangeEnd': '500', 'rangeStart': '0'},
 'E07-4': {'cloud_dataType': 'DIGI1', 'rangeEnd': '500', 'rangeStart': '0'},
 'E07-5': {'cloud_dataType': 'DIGI1', 'rangeEnd': '500', 'rangeStart': '0'},
 'E08': {'cloud_dataType': 'DIGI1', 'rangeEnd': '500', 'rangeStart': '0'},
 'E09': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'E10': {'cloud_dataType': 'DIGI1', 'rangeEnd': '500', 'rangeStart': '0'},
 'E13': {'cloud_dataType': 'TEMP', 'rangeEnd': '20', 'rangeStart': '-20'},
 'E14': {'cloud_dataType': 'DIGI1', 'rangeEnd': '500', 'rangeStart': '0'},
 'E17': {'cloud_dataType': 'DIGI1', 'rangeEnd': '500', 'rangeStart': '10'},
 'E18': {'cloud_dataType': 'TEMP', 'rangeEnd': '10', 'rangeStart': '-10'},
 'E19': {'cloud_dataType': 'DIGI1', 'rangeEnd': '300', 'rangeStart': '0'},
 'F01': {'cloud_dataType': 'ENUM', 'rangeEnd': '4', 'rangeStart': '1'},
 'F02': {'cloud_dataType': 'TEMP', 'rangeEnd': '60', 'rangeStart': '-15'},
 'F03': {'cloud_dataType': 'TEMP', 'rangeEnd': '60', 'rangeStart': '-15'},
 'F05': {'cloud_dataType': 'TEMP', 'rangeEnd': '60', 'rangeStart': '-15'},
 'F06': {'cloud_dataType': 'TEMP', 'rangeEnd': '60', 'rangeStart': '-15'},
 'F10': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'F14': {},
 'F15': {},
 'F17': {},
 'F18': {'cloud_dataType': 'DIGI1', 'rangeEnd': '1300', 'rangeStart': '10'},
 'F19': {'cloud_dataType': 'DIGI1', 'rangeEnd': '1300', 'rangeStart': '10'},
 'F22': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'F23': {'cloud_dataType': 'DIGI1', 'rangeEnd': '1300', 'rangeStart': '10'},
 'F25': {'cloud_dataType': 'DIGI1', 'rangeEnd': '1300', 'rangeStart': '10'},
 'F26': {'cloud_dataType': 'DIGI1', 'rangeEnd': '1300', 'rangeStart': '10'},
 'F27': {},
 'F28': {'cloud_dataType': 'TEMP', 'rangeEnd': '60', 'rangeStart': '-30'},
 'F29': {'cloud_dataType': 'TEMP', 'rangeEnd': '60', 'rangeStart': '-30'},
 'Fault1': {'cloud_dataType': 'BINARY',
            'confidence': 'unknown',
            'dataType': 'bitword16',
            'modbus_register': None,
            'name': 'Fehlerregister 1',
            'note': 'Cloud-only; Modbus-Register noch zuordnen'},
 'Fault2': {'cloud_dataType': 'BINARY',
            'confidence': 'unknown',
            'dataType': 'bitword16',
            'modbus_register': None,
            'name': 'Fehlerregister 2',
            'note': 'Cloud-only; Modbus-Register noch zuordnen'},
 'Fault3': {'cloud_dataType': 'BINARY',
            'confidence': 'unknown',
            'dataType': 'bitword16',
            'modbus_register': None,
            'name': 'Fehlerregister 3',
            'note': 'Cloud-only; Modbus-Register noch zuordnen'},
 'Fault4': {'cloud_dataType': 'BINARY',
            'confidence': 'unknown',
            'dataType': 'bitword16',
            'modbus_register': None,
            'name': 'Fehlerregister 4',
            'note': 'Cloud-only; Modbus-Register noch zuordnen'},
 'Fault5': {'cloud_dataType': 'BINARY',
            'confidence': 'unknown',
            'dataType': 'bitword16',
            'modbus_register': None,
            'name': 'Fehlerregister 5',
            'note': 'Cloud-only; Modbus-Register noch zuordnen'},
 'Fault6': {'cloud_dataType': 'BINARY',
            'confidence': 'unknown',
            'dataType': 'bitword16',
            'modbus_register': None,
            'name': 'Fehlerregister 6',
            'note': 'Cloud-only; Modbus-Register noch zuordnen'},
 'Fault7': {'cloud_dataType': 'BINARY',
            'confidence': 'unknown',
            'dataType': 'bitword16',
            'modbus_register': None,
            'name': 'Fehlerregister 7',
            'note': 'Cloud-only; Modbus-Register noch zuordnen'},
 'Fault8': {'cloud_dataType': 'BINARY',
            'confidence': 'unknown',
            'dataType': 'bitword16',
            'modbus_register': None,
            'name': 'Fehlerregister 8',
            'note': 'Cloud-only; Modbus-Register noch zuordnen'},
 'G01': {'cloud_dataType': 'TEMP', 'rangeEnd': '70', 'rangeStart': '60'},
 'G02': {'cloud_dataType': 'DIGI1', 'rangeEnd': '60', 'rangeStart': '0'},
 'G03': {'cloud_dataType': 'DIGI1', 'rangeEnd': '23', 'rangeStart': '0'},
 'G04': {'cloud_dataType': 'DIGI1', 'rangeEnd': '30', 'rangeStart': '1'},
 'G05': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'H01': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'H05': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'H07': {'cloud_dataType': 'ENUM', 'rangeEnd': '2', 'rangeStart': '0'},
 'H10': {'cloud_dataType': 'DIGI1', 'rangeEnd': '32', 'rangeStart': '1'},
 'H18': {'cloud_dataType': 'ENUM', 'rangeEnd': '3', 'rangeStart': '1'},
 'H20': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'H21': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'H22': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'H25': {'cloud_dataType': 'ENUM', 'rangeEnd': '3', 'rangeStart': '0'},
 'H27': {'cloud_dataType': 'ENUM', 'rangeEnd': '3', 'rangeStart': '0'},
 'H28': {'cloud_dataType': 'ENUM', 'rangeEnd': '2', 'rangeStart': '0'},
 'H29': {'cloud_dataType': 'DIGI1', 'rangeEnd': '20', 'rangeStart': '0'},
 'H30': {'cloud_dataType': 'ENUM',
         'confidence': 'confirmed',
         'local_code': 'H30',
         'modbus_register': 1036,
         'name': 'Indoor Unit Type / Hydraulikmodul-Typ',
         'rangeEnd': '3',
         'rangeStart': '0'},
 'H31': {'cloud_dataType': 'ENUM', 'rangeEnd': '5', 'rangeStart': '0'},
 'H32': {'cloud_dataType': 'DIGI1', 'rangeEnd': '300', 'rangeStart': '1'},
 'H33': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'H36': {'cloud_dataType': 'ENUM', 'rangeEnd': '2', 'rangeStart': '0'},
 'H37': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'H40': {'cloud_dataType': 'ENUM', 'rangeEnd': '3', 'rangeStart': '0'},
 'H42': {'cloud_dataType': 'TEMP', 'rangeEnd': '20.0', 'rangeStart': '-20.0'},
 'H43': {},
 'H45': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'KG1': {'cloud_dataType': 'DIGI1', 'rangeEnd': '65535', 'rangeStart': '0'},
 'KG10': {'cloud_dataType': 'DIGI1', 'rangeEnd': '65535', 'rangeStart': '0'},
 'KG11': {'cloud_dataType': 'DIGI1', 'rangeEnd': '65535', 'rangeStart': '0'},
 'KG12': {'cloud_dataType': 'DIGI1', 'rangeEnd': '65535', 'rangeStart': '0'},
 'KG13~KG28': {'cloud_dataType': 'BINARY', 'rangeEnd': '65535', 'rangeStart': '0'},
 'KG2': {'cloud_dataType': 'DIGI1', 'rangeEnd': '65535', 'rangeStart': '0'},
 'KG29~KG44': {'cloud_dataType': 'BINARY', 'rangeEnd': '65535', 'rangeStart': '0'},
 'KG3': {'cloud_dataType': 'DIGI1', 'rangeEnd': '65535', 'rangeStart': '0'},
 'KG4': {'cloud_dataType': 'DIGI1', 'rangeEnd': '65535', 'rangeStart': '0'},
 'KG45~KG60': {'cloud_dataType': 'BINARY', 'rangeEnd': '65535', 'rangeStart': '0'},
 'KG5': {'cloud_dataType': 'DIGI1', 'rangeEnd': '65535', 'rangeStart': '0'},
 'KG6': {'cloud_dataType': 'DIGI1', 'rangeEnd': '65535', 'rangeStart': '0'},
 'KG7': {'cloud_dataType': 'DIGI1', 'rangeEnd': '65535', 'rangeStart': '0'},
 'KG8': {'cloud_dataType': 'DIGI1', 'rangeEnd': '65535', 'rangeStart': '0'},
 'KG9': {'cloud_dataType': 'DIGI1', 'rangeEnd': '65535', 'rangeStart': '0'},
 'M1 Cooling Target': {'cloud_dataType': 'TEMP',
                       'confidence': 'confirmed',
                       'modbus_register': 1285,
                       'name': 'Timer 1 Kühl-Soll',
                       'rangeEnd': '28.00',
                       'rangeStart': '10.00',
                       'unit': '°C'},
 'M1 End': {'cloud_dataType': 'DIGI1', 'confidence': 'confirmed', 'modbus_register': 1282, 'name': 'Timer 1 Ende'},
 'M1 Heating Target': {'cloud_dataType': 'TEMP',
                       'confidence': 'confirmed',
                       'modbus_register': 1284,
                       'name': 'Timer 1 Heiz-Soll',
                       'rangeEnd': '64.00',
                       'rangeStart': '15.00',
                       'unit': '°C'},
 'M1 Hot Water Target': {'cloud_dataType': 'TEMP',
                         'confidence': 'confirmed',
                         'modbus_register': 1283,
                         'name': 'Timer 1 WW-Soll',
                         'rangeEnd': '53.00',
                         'rangeStart': '15.00',
                         'unit': '°C'},
 'M1 Max. Power': {'cloud_dataType': 'DIGI5',
                   'confidence': 'confirmed',
                   'modbus_register': 1287,
                   'name': 'Timer 1 Max. Leistung',
                   'rangeEnd': '99.9',
                   'rangeStart': '0',
                   'unit': 'kW'},
 'M1 Mode': {'cloud_dataType': 'ENUM', 'confidence': 'confirmed', 'modbus_register': 1286, 'name': 'Timer 1 Modus'},
 'M1 Start': {'cloud_dataType': 'DIGI1', 'confidence': 'confirmed', 'modbus_register': 1281, 'name': 'Timer 1 Start'},
 'M1_2 Enalbe': {'cloud_dataType': 'BINARY',
                 'confidence': 'confirmed',
                 'dataType': 'timer_day_bitword',
                 'modbus_register': 1323,
                 'name': 'Timer 1+2 Aktiv/Tage'},
 'M2 Cooling Target': {'cloud_dataType': 'TEMP',
                       'confidence': 'confirmed',
                       'modbus_register': 1292,
                       'name': 'Timer 2 Kühl-Soll',
                       'rangeEnd': '28.00',
                       'rangeStart': '10.00',
                       'unit': '°C'},
 'M2 End': {'cloud_dataType': 'DIGI1', 'confidence': 'confirmed', 'modbus_register': 1289, 'name': 'Timer 2 Ende'},
 'M2 Heating Target': {'cloud_dataType': 'TEMP',
                       'confidence': 'confirmed',
                       'modbus_register': 1291,
                       'name': 'Timer 2 Heiz-Soll',
                       'rangeEnd': '64.00',
                       'rangeStart': '15.00',
                       'unit': '°C'},
 'M2 Hot Water Target': {'cloud_dataType': 'TEMP',
                         'confidence': 'confirmed',
                         'modbus_register': 1290,
                         'name': 'Timer 2 WW-Soll',
                         'rangeEnd': '53.00',
                         'rangeStart': '15.00',
                         'unit': '°C'},
 'M2 Max. Power': {'cloud_dataType': 'DIGI5',
                   'confidence': 'confirmed',
                   'modbus_register': 1294,
                   'name': 'Timer 2 Max. Leistung',
                   'rangeEnd': '99.9',
                   'rangeStart': '0',
                   'unit': 'kW'},
 'M2 Mode': {'cloud_dataType': 'ENUM', 'confidence': 'confirmed', 'modbus_register': 1293, 'name': 'Timer 2 Modus'},
 'M2 Start': {'cloud_dataType': 'DIGI1', 'confidence': 'confirmed', 'modbus_register': 1288, 'name': 'Timer 2 Start'},
 'M3 Cooling Target': {'cloud_dataType': 'TEMP',
                       'confidence': 'confirmed',
                       'modbus_register': 1299,
                       'name': 'Timer 3 Kühl-Soll',
                       'rangeEnd': '28.00',
                       'rangeStart': '10.00',
                       'unit': '°C'},
 'M3 End': {'cloud_dataType': 'DIGI1', 'confidence': 'confirmed', 'modbus_register': 1296, 'name': 'Timer 3 Ende'},
 'M3 Heating Target': {'cloud_dataType': 'TEMP',
                       'confidence': 'confirmed',
                       'modbus_register': 1298,
                       'name': 'Timer 3 Heiz-Soll',
                       'rangeEnd': '64.00',
                       'rangeStart': '15.00',
                       'unit': '°C'},
 'M3 Hot Water Target': {'cloud_dataType': 'TEMP',
                         'confidence': 'confirmed',
                         'modbus_register': 1297,
                         'name': 'Timer 3 WW-Soll',
                         'rangeEnd': '53.00',
                         'rangeStart': '15.00',
                         'unit': '°C'},
 'M3 Max. Power': {'cloud_dataType': 'DIGI5',
                   'confidence': 'confirmed',
                   'modbus_register': 1301,
                   'name': 'Timer 3 Max. Leistung',
                   'rangeEnd': '99.9',
                   'rangeStart': '0',
                   'unit': 'kW'},
 'M3 Mode': {'cloud_dataType': 'ENUM', 'confidence': 'confirmed', 'modbus_register': 1300, 'name': 'Timer 3 Modus'},
 'M3 Start': {'cloud_dataType': 'DIGI1', 'confidence': 'confirmed', 'modbus_register': 1295, 'name': 'Timer 3 Start'},
 'M3_4 Enalbe': {'cloud_dataType': 'BINARY',
                 'confidence': 'confirmed',
                 'dataType': 'timer_day_bitword',
                 'modbus_register': 1324,
                 'name': 'Timer 3+4 Aktiv/Tage'},
 'M4 Cooling Target': {'cloud_dataType': 'TEMP',
                       'confidence': 'confirmed',
                       'modbus_register': 1306,
                       'name': 'Timer 4 Kühl-Soll',
                       'rangeEnd': '28.00',
                       'rangeStart': '10.00',
                       'unit': '°C'},
 'M4 End': {'cloud_dataType': 'DIGI1', 'confidence': 'confirmed', 'modbus_register': 1303, 'name': 'Timer 4 Ende'},
 'M4 Heating Target': {'cloud_dataType': 'TEMP',
                       'confidence': 'confirmed',
                       'modbus_register': 1305,
                       'name': 'Timer 4 Heiz-Soll',
                       'rangeEnd': '64.00',
                       'rangeStart': '15.00',
                       'unit': '°C'},
 'M4 Hot Water Target': {'cloud_dataType': 'TEMP',
                         'confidence': 'confirmed',
                         'modbus_register': 1304,
                         'name': 'Timer 4 WW-Soll',
                         'rangeEnd': '53.00',
                         'rangeStart': '15.00',
                         'unit': '°C'},
 'M4 Max. Power': {'cloud_dataType': 'DIGI5',
                   'confidence': 'confirmed',
                   'modbus_register': 1308,
                   'name': 'Timer 4 Max. Leistung',
                   'rangeEnd': '99.9',
                   'rangeStart': '0',
                   'unit': 'kW'},
 'M4 Mode': {'cloud_dataType': 'ENUM', 'confidence': 'confirmed', 'modbus_register': 1307, 'name': 'Timer 4 Modus'},
 'M4 Start': {'cloud_dataType': 'DIGI1', 'confidence': 'confirmed', 'modbus_register': 1302, 'name': 'Timer 4 Start'},
 'M5 Cooling Target': {'cloud_dataType': 'TEMP',
                       'confidence': 'confirmed',
                       'modbus_register': 1313,
                       'name': 'Timer 5 Kühl-Soll',
                       'rangeEnd': '28.00',
                       'rangeStart': '10.00',
                       'unit': '°C'},
 'M5 End': {'cloud_dataType': 'DIGI1', 'confidence': 'confirmed', 'modbus_register': 1310, 'name': 'Timer 5 Ende'},
 'M5 Heating Target': {'cloud_dataType': 'TEMP',
                       'confidence': 'confirmed',
                       'modbus_register': 1312,
                       'name': 'Timer 5 Heiz-Soll',
                       'rangeEnd': '64.00',
                       'rangeStart': '15.00',
                       'unit': '°C'},
 'M5 Hot Water Target': {'cloud_dataType': 'TEMP',
                         'confidence': 'confirmed',
                         'modbus_register': 1311,
                         'name': 'Timer 5 WW-Soll',
                         'rangeEnd': '53.00',
                         'rangeStart': '15.00',
                         'unit': '°C'},
 'M5 Max. Power': {'cloud_dataType': 'DIGI5',
                   'confidence': 'confirmed',
                   'modbus_register': 1315,
                   'name': 'Timer 5 Max. Leistung',
                   'rangeEnd': '99.9',
                   'rangeStart': '0',
                   'unit': 'kW'},
 'M5 Mode': {'cloud_dataType': 'ENUM', 'confidence': 'confirmed', 'modbus_register': 1314, 'name': 'Timer 5 Modus'},
 'M5 Start': {'cloud_dataType': 'DIGI1', 'confidence': 'confirmed', 'modbus_register': 1309, 'name': 'Timer 5 Start'},
 'M5_6 Enalbe': {'cloud_dataType': 'BINARY',
                 'confidence': 'confirmed',
                 'dataType': 'timer_day_bitword',
                 'modbus_register': 1325,
                 'name': 'Timer 5+6 Aktiv/Tage'},
 'M6 Cooling Target': {'cloud_dataType': 'TEMP',
                       'confidence': 'confirmed',
                       'modbus_register': 1320,
                       'name': 'Timer 6 Kühl-Soll',
                       'rangeEnd': '28.00',
                       'rangeStart': '10.00',
                       'unit': '°C'},
 'M6 End': {'cloud_dataType': 'DIGI1', 'confidence': 'confirmed', 'modbus_register': 1317, 'name': 'Timer 6 Ende'},
 'M6 Heating Target': {'cloud_dataType': 'TEMP',
                       'confidence': 'confirmed',
                       'modbus_register': 1319,
                       'name': 'Timer 6 Heiz-Soll',
                       'rangeEnd': '64.00',
                       'rangeStart': '15.00',
                       'unit': '°C'},
 'M6 Hot Water Target': {'cloud_dataType': 'TEMP',
                         'confidence': 'confirmed',
                         'modbus_register': 1318,
                         'name': 'Timer 6 WW-Soll',
                         'rangeEnd': '53.00',
                         'rangeStart': '15.00',
                         'unit': '°C'},
 'M6 Max. Power': {'cloud_dataType': 'DIGI5',
                   'confidence': 'confirmed',
                   'modbus_register': 1322,
                   'name': 'Timer 6 Max. Leistung',
                   'rangeEnd': '99.9',
                   'rangeStart': '0',
                   'unit': 'kW'},
 'M6 Mode': {'cloud_dataType': 'ENUM', 'confidence': 'confirmed', 'modbus_register': 1321, 'name': 'Timer 6 Modus'},
 'M6 Start': {'cloud_dataType': 'DIGI1', 'confidence': 'confirmed', 'modbus_register': 1316, 'name': 'Timer 6 Start'},
 'MainBoard Version': {'cloud_dataType': 'DIGI1'},
 'Mode': {'cloud_dataType': 'ENUM',
          'confidence': 'confirmed',
          'local_code': '',
          'modbus_register': 1012,
          'name': 'Sollmodus / Betriebsart',
          'unit': '',
          'write_allowed': True,
          'write_values': {'0': 'Warmwasser', '1': 'Heizen', '2': 'Kühlen', '3': 'WW+Heizen', '4': 'WW+Kühlen'}},
 'ModeState': {'cloud_dataType': 'ENUM',
               'confidence': 'candidate',
               'local_code': '',
               'modbus_register': 2012,
               'name': 'Ist-Betriebsstatus',
               'unit': ''},
 'O01~014': {},
 'O01~023': {'cloud_dataType': 'BINARY',
             'confidence': 'candidate',
             'dataType': 'bitword16',
             'modbus_register': 2019,
             'name': 'Lastausgänge O01~O23'},
 'O15': {'cloud_dataType': 'DIGI1'},
 'O17': {'cloud_dataType': 'DIGI1'},
 'P01': {'cloud_dataType': 'ENUM', 'rangeEnd': '2', 'rangeStart': '0'},
 'P02': {'cloud_dataType': 'DIGI1', 'rangeEnd': '120', 'rangeStart': '1'},
 'P03': {'cloud_dataType': 'DIGI1', 'rangeEnd': '30', 'rangeStart': '1'},
 'P05': {'cloud_dataType': 'ENUM', 'rangeEnd': '2', 'rangeStart': '0'},
 'P06': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'P08': {},
 'P09': {'cloud_dataType': 'DIGI1', 'rangeEnd': '30', 'rangeStart': '0'},
 'P10': {'cloud_dataType': 'DIGI1', 'rangeEnd': '100', 'rangeStart': '0'},
 'P11': {'cloud_dataType': 'TEMP', 'rangeEnd': '20', 'rangeStart': '0'},
 'P12': {'cloud_dataType': 'DIGI1', 'rangeEnd': '10', 'rangeStart': '0'},
 'P13': {'cloud_dataType': 'DIGI1', 'rangeEnd': '200', 'rangeStart': '0'},
 'P14': {'cloud_dataType': 'DIGI1', 'rangeEnd': '6000', 'rangeStart': '0'},
 'P15': {'cloud_dataType': 'DIGI5', 'rangeEnd': '20.0', 'rangeStart': '0.0'},
 'P16': {'cloud_dataType': 'DIGI5', 'rangeEnd': '5.0', 'rangeStart': '0.0'},
 'Power': {'cloud_dataType': 'ENUM',
           'confidence': 'candidate',
           'local_code': '',
           'modbus_register': 1011,
           'name': 'WP Ein/Aus / Power',
           'rangeEnd': '1',
           'rangeStart': '0',
           'unit': '',
           'write_allowed': True,
           'write_values': {'0': 'Aus', '1': 'Ein'}},
 'R01': {'cloud_dataType': 'TEMP', 'rangeEnd': '53.00', 'rangeStart': '15.00'},
 'R02': {'cloud_dataType': 'TEMP', 'rangeEnd': '64.00', 'rangeStart': '15.00'},
 'R03': {'cloud_dataType': 'TEMP', 'rangeEnd': '28.00', 'rangeStart': '10.00'},
 'R04': {'cloud_dataType': 'TEMP', 'rangeEnd': '10', 'rangeStart': '0'},
 'R05': {'cloud_dataType': 'TEMP', 'rangeEnd': '10', 'rangeStart': '0'},
 'R06': {'cloud_dataType': 'TEMP', 'rangeEnd': '10', 'rangeStart': '0'},
 'R07': {'cloud_dataType': 'TEMP', 'rangeEnd': '10', 'rangeStart': '0'},
 'R08': {'cloud_dataType': 'TEMP', 'rangeEnd': '28.00', 'rangeStart': '-30'},
 'R09': {'cloud_dataType': 'TEMP', 'rangeEnd': '80', 'rangeStart': '10.00'},
 'R10': {'cloud_dataType': 'TEMP', 'rangeEnd': '64.00', 'rangeStart': '-30'},
 'R11': {'cloud_dataType': 'TEMP', 'rangeEnd': '99', 'rangeStart': '15.00'},
 'R15': {'cloud_dataType': 'TEMP', 'rangeEnd': '15', 'rangeStart': '0'},
 'R16': {'cloud_dataType': 'TEMP', 'rangeEnd': '10', 'rangeStart': '0'},
 'R17': {'cloud_dataType': 'TEMP', 'rangeEnd': '10', 'rangeStart': '0'},
 'R29': {'cloud_dataType': 'TEMP', 'rangeEnd': '4', 'rangeStart': '-20.00'},
 'R30': {'cloud_dataType': 'TEMP', 'rangeEnd': '-7.00', 'rangeStart': '-35'},
 'R31': {'cloud_dataType': 'TEMP', 'rangeEnd': '85', 'rangeStart': '20'},
 'R32': {'cloud_dataType': 'TEMP', 'rangeEnd': '43.00', 'rangeStart': '0.1'},
 'R33': {'cloud_dataType': 'TEMP', 'rangeEnd': '60', 'rangeStart': '15.00'},
 'R34': {'cloud_dataType': 'TEMP', 'rangeEnd': '85', 'rangeStart': '20'},
 'R35': {'cloud_dataType': 'ENUM', 'rangeEnd': '3', 'rangeStart': '0'},
 'R36': {'cloud_dataType': 'TEMP', 'rangeEnd': '53.00', 'rangeStart': '0'},
 'R37': {'cloud_dataType': 'TEMP', 'rangeEnd': '85', 'rangeStart': '15.00'},
 'R39': {'cloud_dataType': 'TEMP', 'rangeEnd': '22', 'rangeStart': '5'},
 'R42': {'cloud_dataType': 'TEMP', 'rangeEnd': '85', 'rangeStart': '20'},
 'R43': {'cloud_dataType': 'TEMP', 'rangeEnd': '85', 'rangeStart': '20'},
 'R44': {'cloud_dataType': 'TEMP', 'rangeEnd': '85', 'rangeStart': '20'},
 'R45': {'cloud_dataType': 'TEMP', 'rangeEnd': '20', 'rangeStart': '-50'},
 'R46': {'cloud_dataType': 'TEMP', 'rangeEnd': '25', 'rangeStart': '0'},
 'R60': {'cloud_dataType': 'TEMP', 'rangeEnd': '60', 'rangeStart': '0'},
 'R61': {'cloud_dataType': 'TEMP', 'rangeEnd': '60', 'rangeStart': '0'},
 'R62': {'cloud_dataType': 'TEMP', 'rangeEnd': '95', 'rangeStart': '40'},
 'R70': {'cloud_dataType': 'TEMP', 'rangeEnd': '27', 'rangeStart': '5'},
 'R71': {'cloud_dataType': 'TEMP', 'rangeEnd': '3', 'rangeStart': '0.1'},
 'R72': {'cloud_dataType': 'TEMP', 'rangeEnd': '3', 'rangeStart': '0.1'},
 'R73': {'cloud_dataType': 'TEMP', 'rangeEnd': '3', 'rangeStart': '0.1'},
 'R74': {'cloud_dataType': 'TEMP', 'rangeEnd': '3', 'rangeStart': '0.1'},
 'S01~S10': {'cloud_dataType': 'BINARY',
             'confidence': 'candidate',
             'dataType': 'bitword16',
             'modbus_register': 2034,
             'name': 'Schalterzustand S01~S10',
             'note': '16-Bit-Bitwort'},
 'SG Status': {'cloud_dataType': 'ENUM',
               'confidence': 'unknown',
               'modbus_register': None,
               'name': 'SG Status',
               'note': 'Cloud-only; Modbus-Register noch suchen'},
 'SG01': {'cloud_dataType': 'ENUM',
          'confidence': 'confirmed',
          'local_code': 'SG01',
          'modbus_register': 1334,
          'name': 'SG01',
          'rangeEnd': '7',
          'rangeStart': '0'},
 'SG02': {'cloud_dataType': 'DIGI1',
          'confidence': 'candidate',
          'local_code': 'SG02',
          'modbus_register': 1335,
          'name': 'SG02',
          'rangeEnd': '120',
          'rangeStart': '0'},
 'SG03': {'cloud_dataType': 'DIGI5',
          'confidence': 'candidate',
          'local_code': 'SG03',
          'modbus_register': 1336,
          'name': 'SG03',
          'rangeEnd': '99.9',
          'rangeStart': '0'},
 'SG04': {'cloud_dataType': 'DIGI5',
          'confidence': 'candidate',
          'local_code': 'SG04',
          'modbus_register': 1337,
          'name': 'SG04',
          'rangeEnd': '99.9',
          'rangeStart': '0'},
 'SG05': {'cloud_dataType': 'TEMP',
          'confidence': 'candidate',
          'local_code': 'SG05',
          'modbus_register': 1338,
          'name': 'SG05',
          'rangeEnd': '25',
          'rangeStart': '0'},
 'SG06': {'cloud_dataType': 'TEMP',
          'confidence': 'candidate',
          'local_code': 'SG06',
          'modbus_register': 1339,
          'name': 'SG06',
          'rangeEnd': '25',
          'rangeStart': '0'},
 'SG07': {'cloud_dataType': 'TEMP',
          'confidence': 'candidate',
          'local_code': 'SG07',
          'modbus_register': 1340,
          'name': 'SG07',
          'rangeEnd': '25',
          'rangeStart': '0'},
 'SG08': {'cloud_dataType': 'ENUM',
          'confidence': 'confirmed',
          'local_code': 'SG08',
          'modbus_register': 1341,
          'name': 'Heizstab ein bei SG Mode4',
          'rangeEnd': '1',
          'rangeStart': '0'},
 'T01': {'cloud_dataType': 'TEMP'},
 'T02': {'cloud_dataType': 'TEMP'},
 'T03': {'cloud_dataType': 'TEMP'},
 'T04': {'cloud_dataType': 'TEMP'},
 'T05': {'cloud_dataType': 'TEMP'},
 'T06': {'cloud_dataType': 'TEMP'},
 'T07': {'cloud_dataType': 'TEMP'},
 'T08': {'cloud_dataType': 'TEMP'},
 'T09': {'cloud_dataType': 'TEMP'},
 'T10': {'cloud_dataType': 'TEMP'},
 'T11': {'cloud_dataType': 'TEMP'},
 'T12': {'cloud_dataType': 'TEMP'},
 'T15': {'cloud_dataType': 'DIGI5',
         'confidence': 'candidate',
         'local_code': 'T15',
         'modbus_register': 2069,
         'name': 'Druck',
         'unit': 'bar'},
 'T27': {'cloud_dataType': 'DIGI1'},
 'T28': {'cloud_dataType': 'DIGI1'},
 'T29': {'cloud_dataType': 'DIGI1'},
 'T30': {'cloud_dataType': 'DIGI1'},
 'T31': {'cloud_dataType': 'DIGI1'},
 'T32': {'cloud_dataType': 'DIGI1'},
 'T33': {'cloud_dataType': 'TEMP'},
 'T34': {'cloud_dataType': 'DIGI1',
         'confidence': 'confirmed',
         'local_code': 'T34',
         'modbus_register': 2062,
         'name': 'AC Eingangsspannung',
         'note': 'T34 = 2062, nicht 2057',
         'unit': 'V'},
 'T35': {'cloud_dataType': 'DIGI5'},
 'T36': {'cloud_dataType': 'DIGI5',
         'confidence': 'candidate',
         'local_code': 'T36',
         'modbus_register': 2042,
         'name': 'Strom / Current',
         'unit': 'A'},
 'T37': {'cloud_dataType': 'DIGI1'},
 'T38': {'cloud_dataType': 'TEMP'},
 'T39': {'cloud_dataType': 'DIGI9'},
 'T40': {'cloud_dataType': 'TEMP'},
 'T41': {'cloud_dataType': 'TEMP'},
 'T42': {'cloud_dataType': 'TEMP'},
 'T43': {'cloud_dataType': 'TEMP'},
 'T44': {'cloud_dataType': 'TEMP'},
 'T46': {'cloud_dataType': 'TEMP'},
 'T47': {'cloud_dataType': 'DIGI1'},
 'T48': {'cloud_dataType': 'DIGI6'},
 'TimerMuteOffHour': {'cloud_dataType': 'DIGI1', 'rangeEnd': '23', 'rangeStart': '0'},
 'TimerMuteOffMinute': {'cloud_dataType': 'DIGI1', 'rangeEnd': '59', 'rangeStart': '0'},
 'TimerMuteOnHour': {'cloud_dataType': 'DIGI1', 'rangeEnd': '23', 'rangeStart': '0'},
 'TimerMuteOnMinute': {'cloud_dataType': 'DIGI1', 'rangeEnd': '59', 'rangeStart': '0'},
 'Timer_Mute_Off_En': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'Timer_Mute_On_En': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'W1 End': {'cloud_dataType': 'DIGI1'},
 'W1 Start': {'cloud_dataType': 'DIGI1'},
 'W1_2 Enalbe': {'cloud_dataType': 'BINARY'},
 'W2 End': {'cloud_dataType': 'DIGI1'},
 'W2 Start': {'cloud_dataType': 'DIGI1'},
 'W3 Enalbe': {'cloud_dataType': 'BINARY'},
 'W3 End': {'cloud_dataType': 'DIGI1'},
 'W3 Start': {'cloud_dataType': 'DIGI1'},
 'Z01': {'cloud_dataType': 'ENUM', 'rangeEnd': '9', 'rangeStart': '0'},
 'Z02': {'cloud_dataType': 'TEMP', 'rangeEnd': '75', 'rangeStart': '10'},
 'Z03': {'cloud_dataType': 'TEMP', 'rangeEnd': '10', 'rangeStart': '0'},
 'Z04': {'cloud_dataType': 'TEMP', 'rangeEnd': '75', 'rangeStart': '10'},
 'Z05': {'cloud_dataType': 'TEMP', 'rangeEnd': '10', 'rangeStart': '0'},
 'Z06': {'cloud_dataType': 'TEMP', 'rangeEnd': '64.00', 'rangeStart': '15.00'},
 'Z07': {'cloud_dataType': 'TEMP', 'rangeEnd': '40.00', 'rangeStart': '15.00'},
 'Z08': {'cloud_dataType': 'DIGI1', 'rangeEnd': '100', 'rangeStart': '0'},
 'Z09': {'cloud_dataType': 'DIGI1', 'rangeEnd': '2000', 'rangeStart': '0'},
 'Z10': {'cloud_dataType': 'DIGI1', 'rangeEnd': '2000', 'rangeStart': '0'},
 'Z11': {'cloud_dataType': 'DIGI5', 'rangeEnd': '10', 'rangeStart': '0'},
 'Z12': {'cloud_dataType': 'DIGI5', 'rangeEnd': '10', 'rangeStart': '0'},
 'Z13': {'cloud_dataType': 'DIGI1', 'rangeEnd': '20', 'rangeStart': '1'},
 'Z14': {'cloud_dataType': 'DIGI1', 'rangeEnd': '100', 'rangeStart': '0'},
 'Z15': {'cloud_dataType': 'TEMP', 'rangeEnd': '99', 'rangeStart': '$1164'},
 'Z16': {},
 'Z17': {'cloud_dataType': 'ENUM', 'rangeEnd': '2', 'rangeStart': '0'},
 'Z19': {'cloud_dataType': 'TEMP', 'rangeEnd': '25', 'rangeStart': '0'},
 'Z20': {'cloud_dataType': 'ENUM', 'rangeEnd': '1', 'rangeStart': '0'},
 'Z21': {'cloud_dataType': 'ENUM', 'rangeEnd': '2', 'rangeStart': '0'},
 'Zone 1 Room Temp': {'cloud_dataType': 'TEMP'},
 'Zone 2 Cure Slope': {'cloud_dataType': 'DIGI5', 'rangeEnd': '4', 'rangeStart': '0'},
 'Zone 2 Curve Offset': {'cloud_dataType': 'DIGI5', 'rangeEnd': '40.00', 'rangeStart': '15.00'},
 'Zone 2 Mixing Temp': {'cloud_dataType': 'TEMP'},
 'Zone 2 Room Temp': {'cloud_dataType': 'TEMP'},
 'Zone 2 Water Target': {'cloud_dataType': 'TEMP'},
 'app_heartbeat': {'cloud_dataType': 'DIGI1', 'rangeEnd': '23205', 'rangeStart': '0'},
 'code_version': {'cloud_dataType': 'DIGI5'},
 'compensate_offset': {'cloud_dataType': 'TEMP', 'rangeEnd': '64.00', 'rangeStart': '15.00'},
 'compensate_slope': {'cloud_dataType': 'DIGI5', 'rangeEnd': '3.5', 'rangeStart': '0'},
 'hanControl': {'cloud_dataType': 'BINARY'}}

# Erlaubte, bewusst kleine Schreibtests. Standard-UI bleibt read-only, bis der
# Benutzer explizit Schreibtest aktiviert und bestaetigt.
WARMLINK_CLOUD_WRITE_TEST_CODES: dict[str, dict[str, object]] = {
    "Mode": {
        "name": "Betriebsart umschalten",
        "values": {"0": "Warmwasser", "1": "Heizen", "2": "Kühlen", "3": "WW+Heizen", "4": "WW+Kühlen"},
        "note": "Testcode fuer Heizen/Kuehlen/WW-Umschaltung. Nur mit Extra-Bestaetigung senden.",
    },
    "Power": {
        "name": "WP Ein/Aus",
        "values": {"0": "Aus", "1": "Ein"},
        "note": "Optionaler Schreibtest; Power-Mapping ist noch candidate.",
    },
}


def cloud_hint(code: str) -> dict[str, object]:
    return WARMLINK_CLOUD_CODE_HINTS.get(str(code), {})


def cloud_modbus_register(code: str) -> int | None:
    reg = cloud_hint(code).get("modbus_register")
    try:
        return int(reg) if reg not in (None, "") else None
    except Exception:
        return None


def code_display_name(code: str) -> str:
    hint = cloud_hint(code)
    return str(hint.get("name") or code)


def code_unit(code: str) -> str:
    return str(cloud_hint(code).get("unit") or "")


def code_confidence(code: str) -> str:
    return str(cloud_hint(code).get("confidence") or "")
